# Generated by Django 4.1.4 on 2023-10-04 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_time', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.customer')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('SberPay', 'SberPay'), ('GooglePay', 'GooglePay'), ('Card', 'Card'), ('QR-code', 'QR_code')], max_length=10)),
            ],
            options={
                'db_table': 'payment_type',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('description', models.TextField()),
                ('quantity_in_stock', models.IntegerField()),
                ('prime_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.order')),
                ('payment_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.paymenttype')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.product')),
            ],
            options={
                'db_table': 'order_product',
            },
        ),
    ]
